spring:
  security:
    oauth2:
      client:
        registration:
          shu:
#            client-id: Iyg54OBe127Oh0TGOch7O7T7d0p25c14
#            client-secret: PyTEIrJcoNmpDCvntmYgXzXM6OuQpaMV
            client-id: 21wL392i20II0zYD2f03jD223fiL7L68
            client-secret: 8O3lcVSj2WUbxZRJcUzQaP7LbD6QRxzA
            authorization-grant-type: authorization_code
#            redirect-uri: '{baseScheme}://{baseHost}{basePort}{basePath}/oauth2/callback/{registrationId}'
            redirect-uri: 'https://sdtzxx.shu.edu.cn/api/oauth2/callback/{registrationId}'
            scope: read, write
        provider:
          shu:
            authorization-uri: https://newsso.shu.edu.cn/oauth/authorize
            token-uri: https://newsso.shu.edu.cn/oauth/token
            user-info-uri: https://newsso.shu.edu.cn/rest/user/getInfo
            user-name-attribute: userid
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with:
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: online-token-
  # 验证码
  code-key: code-key-
  # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认1小时，单位毫秒
  renew: 3600000